// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafioTecnicoAvanadeApi.Infrastrutura;

#nullable disable

namespace desafioTecnicoAvanadeApi.infraestrutura.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20251130194421_createInicial")]
    partial class createInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("desafioTecnicoAvanadeApi.Entitades.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TabelaClientes");
                });

            modelBuilder.Entity("desafioTecnicoAvanadeApi.Entitades.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientePedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PedidosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientePedidoId");

                    b.HasIndex("PedidosId");

                    b.ToTable("TabelaPedidos");
                });

            modelBuilder.Entity("desafioTecnicoAvanadeApi.Entitades.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TabelaProdutos");
                });

            modelBuilder.Entity("desafioTecnicoAvanadeApi.Entitades.Pedidos", b =>
                {
                    b.HasOne("desafioTecnicoAvanadeApi.Entitades.Clientes", "ClientePedido")
                        .WithMany()
                        .HasForeignKey("ClientePedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("desafioTecnicoAvanadeApi.Entitades.Pedidos", null)
                        .WithMany("ListProdutos")
                        .HasForeignKey("PedidosId");

                    b.Navigation("ClientePedido");
                });

            modelBuilder.Entity("desafioTecnicoAvanadeApi.Entitades.Pedidos", b =>
                {
                    b.Navigation("ListProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
